image: ruby:3.1

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
    - apt-get update -y
    - apt-get install -y wget default-jre default-jdk graphviz
    - wget https://github.com/plantuml/plantuml/releases/download/v1.2022.13/plantuml-1.2022.13.jar -O plantuml.jar
    - echo "#!/bin/bash" > plantuml
    - echo "java -jar $PWD/plantuml.jar \"\$1\" \"\$2\"" >> plantuml
    - mv plantuml /usr/bin/plantuml
    - chmod +x /usr/bin/plantuml
    - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
    - master
    - feature/gitlab-no-pages

pages:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install -y wget default-jre default-jdk graphviz
    - wget https://github.com/plantuml/plantuml/releases/download/v1.2022.13/plantuml-1.2022.13.jar -O plantuml.jar
    - echo "#!/bin/bash" > plantuml
    - echo "java -jar $PWD/plantuml.jar \"\$1\" \"\$2\"" >> plantuml
    - mv plantuml /usr/bin/plantuml
    - chmod +x /usr/bin/plantuml
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
    - feature/gitlab-no-pages
