# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ingegneria del software
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Appunti del corso di Ingegneria del software
baseurl: "/sweng" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site

# Outputting
permalink: /:year/:title

# Build settings
markdown: kramdown
exclude:
  - README.md
  - Gemfile*
  - .git*
  - .dockerfile
  - Dockerfile
  - docker-run.sh
  - plantuml.jar

plugins:
  - jekyll-toc
  - jekyll-responsive-image
  - jekyll-plantuml

# responsive-image settings
responsive_image:
  template: _includes/image.html
  sizes:
    - width: 320
    - width: 480
    - width: 800
  base_path: assets
  output_path_format: assets/resized/%{width}/%{basename}
